[package]
name = "hwid_guard"
version = "0.1.0"
edition = "2021"

[lib]
name = "hwid_guard"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
chrono = "0.4"
hex = "0.4"
