name: Build Rust Guard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Install dependencies for Windows
      - name: Install MinGW on Windows
        if: matrix.os == 'windows-latest'
        run: choco install mingw -y

      # Build Rust library
      - name: Build Rust library
        run: |
          cd electron-client/native
          cargo build --release

      # Prepare artifact folder
      - name: Prepare artifact folder
        run: mkdir -p artifact

      # Copy built library based on OS
      - name: Copy binary - Windows
        if: matrix.os == 'windows-latest'
        run: copy electron-client\native\target\release\hwid_guard.dll artifact\

      - name: Copy binary - macOS
        if: matrix.os == 'macos-latest'
        run: cp electron-client/native/target/release/libhwid_guard.dylib artifact/

      - name: Copy binary - Linux
        if: matrix.os == 'ubuntu-latest'
        run: cp electron-client/native/target/release/libhwid_guard.so artifact/

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hwid-guard-${{ matrix.os }}
          path: artifact/
